# Generated by Django 4.2.7 on 2023-11-14 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accesorios",
            fields=[
                ("id_accesorio", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id_cliente", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("apellido", models.CharField(max_length=255)),
                ("telefono", models.CharField(max_length=255)),
                ("correo", models.EmailField(max_length=254)),
                ("direccion", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                ("id_empleado", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("apellido", models.CharField(max_length=255)),
                ("direccion", models.CharField(max_length=255)),
                ("fecha_inicio", models.DateField()),
                ("salario", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("GERENTE", "Gerente"),
                            ("JEFE DE TALLER", "Jefe de Taller"),
                            ("ASESOR COMERCIAL", "Asesor Comercial"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JefeTaller",
            fields=[
                ("id_jefetaller", models.AutoField(primary_key=True, serialize=False)),
                ("correo", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                ("cod_sucursal", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("direccion", models.CharField(max_length=255)),
                ("ciudad", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="VehiculoNuevo",
            fields=[
                (
                    "VIN",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("marca", models.CharField(max_length=255)),
                ("modelo", models.CharField(max_length=255)),
                ("anio", models.IntegerField()),
                ("color", models.CharField(max_length=255)),
                ("tipo_combustible", models.CharField(max_length=255)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cod_sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Application.sucursal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehiculoCliente",
            fields=[
                (
                    "placa",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("marca", models.CharField(max_length=255)),
                ("modelo", models.CharField(max_length=255)),
                ("anio", models.IntegerField()),
                ("color", models.CharField(max_length=255)),
                ("VIN", models.CharField(max_length=255)),
                ("tipo_combustible", models.CharField(max_length=255)),
                (
                    "id_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Application.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id_usuario",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("contrasena", models.CharField(max_length=255)),
                (
                    "id_empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Application.empleado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Repuestos",
            fields=[
                (
                    "referencia_repuesto",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("marca", models.CharField(max_length=255)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cod_sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Application.sucursal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdenReparacion",
            fields=[
                ("numero_orden", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_inicio", models.DateField()),
                ("fecha_entrega", models.DateField()),
                (
                    "id_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Application.cliente",
                    ),
                ),
                (
                    "id_jefetaller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Application.jefetaller",
                    ),
                ),
                (
                    "placa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Application.vehiculocliente",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jefetaller",
            name="cod_sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Application.sucursal"
            ),
        ),
        migrations.AddField(
            model_name="jefetaller",
            name="id_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Application.usuario"
            ),
        ),
        migrations.CreateModel(
            name="Gerente",
            fields=[
                ("id_gerente", models.AutoField(primary_key=True, serialize=False)),
                ("correo", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=255)),
                (
                    "cod_sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Application.sucursal",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Application.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                ("id_cotizacion", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_cotizacion", models.DateField()),
                ("descripcion", models.TextField()),
                (
                    "VIN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Application.vehiculonuevo",
                    ),
                ),
                (
                    "cod_sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Application.sucursal",
                    ),
                ),
                (
                    "id_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Application.cliente",
                    ),
                ),
                (
                    "referencia_repuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Application.repuestos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AsesorComercial",
            fields=[
                ("id_asesor", models.AutoField(primary_key=True, serialize=False)),
                ("correo", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=255)),
                (
                    "cod_sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Application.sucursal",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Application.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CotizacionAccesorios",
            fields=[
                (
                    "id_cotizacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="Application.cotizacion",
                    ),
                ),
                (
                    "id_accesorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Application.accesorios",
                    ),
                ),
            ],
        ),
    ]
