# Generated by Django 4.2.7 on 2023-11-17 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_alter_asesorcomercial_id_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id_cliente',
            new_name='id',
        ),
    ]
