# Generated by Django 4.2.7 on 2023-11-17 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_rename_id_cliente_cliente_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id',
            new_name='id_cliente',
        ),
    ]
